name: user-service
services:
  user-php:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    volumes:
      - ../:/var/www
    depends_on:
      - postgres
    networks:
      - user-service-network
      - microservices-network

  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ../:/var/www
    depends_on:
      - user-php
    networks:
      user-service-network:
      microservices-network:
        aliases:
          - user-service

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-service-network

volumes:
  postgres_data:

networks:
  user-service-network:
    driver: bridge
  microservices-network:
    external: true
